/*
=========================================
Kale Farm Manager v2.0
app.js
Main Application
=========================================
*/

document.addEventListener("DOMContentLoaded", () => {

    // -------------------------
        // Navigation
            // -------------------------

                const buttons = document.querySelectorAll(".nav-btn");
                    const pages = document.querySelectorAll(".page");

                        buttons.forEach(button => {

                                button.addEventListener("click", () => {

                                            const page = button.dataset.page;

                                                        buttons.forEach(btn => btn.classList.remove("active"));
                                                                    button.classList.add("active");

                                                                                pages.forEach(section => {

                                                                                                if (section.id === page) {
                                                                                                                    section.classList.add("active");
                                                                                                                                    } else {
                                                                                                                                                        section.classList.remove("active");
                                                                                                                                                                        }

                                                                                                                                                                                    });

                                                                                                                                                                                                Dashboard.refresh();
                                                                                                                                                                                                            Reports.render();

                                                                                                                                                                                                                    });

                                                                                                                                                                                                                        });

                                                                                                                                                                                                                            // -------------------------
                                                                                                                                                                                                                                // Clear All Data
                                                                                                                                                                                                                                    // -------------------------

                                                                                                                                                                                                                                        const clearBtn = document.getElementById("clearBtn");

                                                                                                                                                                                                                                            if (clearBtn) {

                                                                                                                                                                                                                                                    clearBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                if (!confirm("Are you sure you want to delete all farm records?")) {
                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                        Storage.clearAll();

                                                                                                                                                                                                                                                                                                                    Expenses.render();
                                                                                                                                                                                                                                                                                                                                Harvests.render();
                                                                                                                                                                                                                                                                                                                                            Dashboard.refresh();
                                                                                                                                                                                                                                                                                                                                                        Reports.render();

                                                                                                                                                                                                                                                                                                                                                                    alert("All data has been cleared.");

                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                    // -------------------------
                                                                                                                                                                                                                                                                                                                                                                                        // Backup Data
                                                                                                                                                                                                                                                                                                                                                                                            // -------------------------

                                                                                                                                                                                                                                                                                                                                                                                                const backupBtn = document.getElementById("backupBtn");

                                                                                                                                                                                                                                                                                                                                                                                                    if (backupBtn) {

                                                                                                                                                                                                                                                                                                                                                                                                            backupBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                        const data = Storage.exportData();

                                                                                                                                                                                                                                                                                                                                                                                                                                    const blob = new Blob(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    [JSON.stringify(data, null, 2)],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { type: "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const url = URL.createObjectURL(blob);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const a = document.createElement("a");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                a.download = "kale-farm-backup.json";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a.click();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        URL.revokeObjectURL(url);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // -------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Restore Data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // -------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const restoreBtn = document.getElementById("restoreBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (restoreBtn) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                restoreBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const input = document.createElement("input");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input.type = "file";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input.accept = ".json";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input.onchange = (event) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const file = event.target.files[0];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!file) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const reader = new FileReader();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reader.onload = () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const data = JSON.parse(reader.result);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Storage.importData(data);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expenses.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Harvests.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dashboard.refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Reports.render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Backup restored successfully.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert("Invalid backup file.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reader.readAsText(file);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input.click();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // -------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initial Refresh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // -------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Dashboard.refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Expenses.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Harvests.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Reports.render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });