/*
=========================================
Kale Farm Manager v2.1 Professional
app.js
=========================================
*/

document.addEventListener("DOMContentLoaded", () => {

    // =========================
        // Navigation
            // =========================

                const navButtons = document.querySelectorAll(".nav-btn");
                    const pages = document.querySelectorAll(".page");

                        function showPage(pageId) {

                                pages.forEach(page => {
                                            page.classList.remove("active");
                                                    });

                                                            navButtons.forEach(btn => {
                                                                        btn.classList.remove("active");
                                                                                });

                                                                                        const page = document.getElementById(pageId);

                                                                                                if (page) {
                                                                                                            page.classList.add("active");
                                                                                                                    }

                                                                                                                            const activeButton =
                                                                                                                                        document.querySelector(`.nav-btn[data-page="${pageId}"]`);

                                                                                                                                                if (activeButton) {
                                                                                                                                                            activeButton.classList.add("active");
                                                                                                                                                                    }

                                                                                                                                                                            Dashboard.refresh();
                                                                                                                                                                                    Reports.render();

                                                                                                                                                                                        }

                                                                                                                                                                                            navButtons.forEach(button => {

                                                                                                                                                                                                    button.addEventListener("click", () => {

                                                                                                                                                                                                                showPage(button.dataset.page);

                                                                                                                                                                                                                        });

                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                    // Backup
                                                                                                                                                                                                                                        // =========================

                                                                                                                                                                                                                                            const backupBtn = document.getElementById("backupBtn");

                                                                                                                                                                                                                                                if (backupBtn) {

                                                                                                                                                                                                                                                        backupBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                    const data = Storage.exportData();

                                                                                                                                                                                                                                                                                const blob = new Blob(
                                                                                                                                                                                                                                                                                                [JSON.stringify(data, null, 2)],
                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                    type: "application/json"
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                            const url = URL.createObjectURL(blob);

                                                                                                                                                                                                                                                                                                                                                                                        const link = document.createElement("a");

                                                                                                                                                                                                                                                                                                                                                                                                    link.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                link.download = "kale-farm-manager-backup.json";

                                                                                                                                                                                                                                                                                                                                                                                                                            document.body.appendChild(link);

                                                                                                                                                                                                                                                                                                                                                                                                                                        link.click();

                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.removeChild(link);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                URL.revokeObjectURL(url);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Restore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const restoreBtn = document.getElementById("restoreBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (restoreBtn) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        restoreBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const input = document.createElement("input");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input.type = "file";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            input.accept = ".json";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input.addEventListener("change", event => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const file = event.target.files[0];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!file) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const reader = new FileReader();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reader.onload = e => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = JSON.parse(e.target.result);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Storage.importData(data);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Expenses.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Harvests.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Dashboard.refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Reports.render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert("Backup restored successfully.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert("Invalid backup file.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reader.readAsText(file);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            input.click();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Clear Data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // =========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const clearBtn = document.getElementById("clearBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (clearBtn) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    clearBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const confirmed = confirm(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Delete all farm records?"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!confirmed) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Storage.clearAll();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Expenses.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Harvests.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Dashboard.refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Reports.render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert("All data has been deleted.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Initial Load
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showPage("dashboard");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Expenses.render();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Harvests.render();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });