/*
=========================================
Kale Farm Manager v2.2
dashboard.js
=========================================
*/

const Dashboard = {

    currency(value) {
            return "KES " + Number(value).toLocaleString("en-KE", {
                        minimumFractionDigits: 2,
                                    maximumFractionDigits: 2
                                            });
                                                },

                                                    refresh() {

                                                            const totalExpenses = Storage.getTotalExpenses();
                                                                    const totalHarvest = Storage.getTotalHarvestKg();
                                                                            const totalIncome = Storage.getTotalIncome();
                                                                                    const profit = Storage.getProfit();

                                                                                            // Dashboard totals
                                                                                                    document.getElementById("totalExpenses").textContent =
                                                                                                                this.currency(totalExpenses);

                                                                                                                        document.getElementById("totalHarvest").textContent =
                                                                                                                                    totalHarvest.toLocaleString("en-KE") + " kg";

                                                                                                                                            document.getElementById("totalIncome").textContent =
                                                                                                                                                        this.currency(totalIncome);

                                                                                                                                                                const profitElement = document.getElementById("profit");

                                                                                                                                                                        profitElement.textContent = this.currency(profit);

                                                                                                                                                                                profitElement.style.color =
                                                                                                                                                                                            profit >= 0 ? "#ffffff" : "#ffeb3b";

                                                                                                                                                                                                    // Today's Date
                                                                                                                                                                                                            const today = new Date();

                                                                                                                                                                                                                    const currentDate = document.getElementById("currentDate");

                                                                                                                                                                                                                            if (currentDate) {

                                                                                                                                                                                                                                        currentDate.textContent =
                                                                                                                                                                                                                                                        today.toLocaleDateString("en-KE", {
                                                                                                                                                                                                                                                                            weekday: "long",
                                                                                                                                                                                                                                                                                                day: "numeric",
                                                                                                                                                                                                                                                                                                                    month: "long",
                                                                                                                                                                                                                                                                                                                                        year: "numeric"
                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                        // Record Counts

                                                                                                                                                                                                                                                                                                                                                                                const expenseCount =
                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("expenseCount");

                                                                                                                                                                                                                                                                                                                                                                                                    if (expenseCount) {

                                                                                                                                                                                                                                                                                                                                                                                                                expenseCount.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                Storage.getExpenses().length;

                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                const harvestCount =
                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("harvestCount");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (harvestCount) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                harvestCount.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Storage.getHarvests().length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Welcome Message

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const hour = today.getHours();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let greeting = "Welcome";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (hour < 12) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    greeting = "🌅 Good Morning";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (hour < 17) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        greeting = "☀️ Good Afternoon";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            greeting = "🌙 Good Evening";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const welcome =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("welcomeMessage");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (welcome) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            welcome.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `${greeting}! Welcome back to Kale Farm Manager.`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.addEventListener("DOMContentLoaded", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dashboard.refresh();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });