/*
=========================================
Kale Farm Manager v2.0
expenses.js
Expense Management
=========================================
*/

const Expenses = {

    init() {
            const form = document.getElementById("expenseForm");

                    if (form) {
                                form.addEventListener("submit", (e) => {
                                                e.preventDefault();
                                                                this.saveExpense();
                                                                            });
                                                                                    }

                                                                                            this.render();
                                                                                                },

                                                                                                    saveExpense() {

                                                                                                            const date = document.getElementById("expenseDate").value;
                                                                                                                    const category = document.getElementById("expenseCategory").value.trim();
                                                                                                                            const amount = Number(document.getElementById("expenseAmount").value);

                                                                                                                                    if (!date || !category || amount <= 0) {
                                                                                                                                                alert("Please fill in all expense details.");
                                                                                                                                                            return;
                                                                                                                                                                    }

                                                                                                                                                                            Storage.addExpense({
                                                                                                                                                                                        id: Date.now(),
                                                                                                                                                                                                    date,
                                                                                                                                                                                                                category,
                                                                                                                                                                                                                            amount
                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                            document.getElementById("expenseForm").reset();

                                                                                                                                                                                                                                                    this.render();
                                                                                                                                                                                                                                                            Dashboard.refresh();

                                                                                                                                                                                                                                                                    alert("Expense saved successfully.");
                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                            render() {

                                                                                                                                                                                                                                                                                    const list = document.getElementById("expenseList");

                                                                                                                                                                                                                                                                                            if (!list) return;

                                                                                                                                                                                                                                                                                                    const expenses = Storage.getExpenses();

                                                                                                                                                                                                                                                                                                            if (expenses.length === 0) {
                                                                                                                                                                                                                                                                                                                        list.innerHTML = `
                                                                                                                                                                                                                                                                                                                                        <div class="empty">
                                                                                                                                                                                                                                                                                                                                                            No expenses recorded yet.
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                    expenses.sort((a, b) => b.id - a.id);

                                                                                                                                                                                                                                                                                                                                                                                                                            list.innerHTML = expenses.map(expense => `
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="list-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="list-title">${expense.category}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="list-subtitle">${expense.date}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KES ${Number(expense.amount).toLocaleString("en-KE", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minimumFractionDigits: 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.addEventListener("DOMContentLoaded", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expenses.init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });