/*
=========================================
Kale Farm Manager v2.0
harvests.js
Harvest Management
=========================================
*/

const Harvests = {

    init() {
            const form = document.getElementById("harvestForm");

                    if (form) {
                                form.addEventListener("submit", (e) => {
                                                e.preventDefault();
                                                                this.saveHarvest();
                                                                            });
                                                                                    }

                                                                                            this.render();
                                                                                                },

                                                                                                    saveHarvest() {

                                                                                                            const date = document.getElementById("harvestDate").value;
                                                                                                                    const weight = Number(document.getElementById("harvestWeight").value);
                                                                                                                            const price = Number(document.getElementById("harvestPrice").value);

                                                                                                                                    if (!date || weight <= 0 || price <= 0) {
                                                                                                                                                alert("Please enter valid harvest details.");
                                                                                                                                                            return;
                                                                                                                                                                    }

                                                                                                                                                                            Storage.addHarvest({
                                                                                                                                                                                        id: Date.now(),
                                                                                                                                                                                                    date,
                                                                                                                                                                                                                weight,
                                                                                                                                                                                                                            price
                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                            document.getElementById("harvestForm").reset();

                                                                                                                                                                                                                                                    this.render();
                                                                                                                                                                                                                                                            Dashboard.refresh();

                                                                                                                                                                                                                                                                    alert("Harvest saved successfully.");
                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                            render() {

                                                                                                                                                                                                                                                                                    const list = document.getElementById("harvestList");

                                                                                                                                                                                                                                                                                            if (!list) return;

                                                                                                                                                                                                                                                                                                    const harvests = Storage.getHarvests();

                                                                                                                                                                                                                                                                                                            if (harvests.length === 0) {
                                                                                                                                                                                                                                                                                                                        list.innerHTML = `
                                                                                                                                                                                                                                                                                                                                        <div class="empty">
                                                                                                                                                                                                                                                                                                                                                            No harvest records yet.
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                    harvests.sort((a, b) => b.id - a.id);

                                                                                                                                                                                                                                                                                                                                                                                                                            list.innerHTML = harvests.map(item => `
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="list-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="list-title">${item.weight} kg</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="list-subtitle">${item.date}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    KES ${Number(item.price).toLocaleString("en-KE", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minimumFractionDigits: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maximumFractionDigits: 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener("DOMContentLoaded", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Harvests.init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });