/*
=========================================
Kale Farm Manager v2.0
storage.js
Handles Local Storage
=========================================
*/

const STORAGE_KEYS = {
    expenses: "kfm_expenses",
        harvests: "kfm_harvests"
        };

        const Storage = {

            // -------------------------
                // Expenses
                    // -------------------------

                        getExpenses() {
                                return JSON.parse(localStorage.getItem(STORAGE_KEYS.expenses)) || [];
                                    },

                                        saveExpenses(expenses) {
                                                localStorage.setItem(
                                                            STORAGE_KEYS.expenses,
                                                                        JSON.stringify(expenses)
                                                                                );
                                                                                    },

                                                                                        addExpense(expense) {
                                                                                                const expenses = this.getExpenses();
                                                                                                        expenses.push(expense);
                                                                                                                this.saveExpenses(expenses);
                                                                                                                    },

                                                                                                                        // -------------------------
                                                                                                                            // Harvests
                                                                                                                                // -------------------------

                                                                                                                                    getHarvests() {
                                                                                                                                            return JSON.parse(localStorage.getItem(STORAGE_KEYS.harvests)) || [];
                                                                                                                                                },

                                                                                                                                                    saveHarvests(harvests) {
                                                                                                                                                            localStorage.setItem(
                                                                                                                                                                        STORAGE_KEYS.harvests,
                                                                                                                                                                                    JSON.stringify(harvests)
                                                                                                                                                                                            );
                                                                                                                                                                                                },

                                                                                                                                                                                                    addHarvest(harvest) {
                                                                                                                                                                                                            const harvests = this.getHarvests();
                                                                                                                                                                                                                    harvests.push(harvest);
                                                                                                                                                                                                                            this.saveHarvests(harvests);
                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                    // -------------------------
                                                                                                                                                                                                                                        // Totals
                                                                                                                                                                                                                                            // -------------------------

                                                                                                                                                                                                                                                getTotalExpenses() {
                                                                                                                                                                                                                                                        return this.getExpenses().reduce((total, item) => {
                                                                                                                                                                                                                                                                    return total + Number(item.amount);
                                                                                                                                                                                                                                                                            }, 0);
                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                    getTotalHarvestKg() {
                                                                                                                                                                                                                                                                                            return this.getHarvests().reduce((total, item) => {
                                                                                                                                                                                                                                                                                                        return total + Number(item.weight);
                                                                                                                                                                                                                                                                                                                }, 0);
                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                        getTotalIncome() {
                                                                                                                                                                                                                                                                                                                                return this.getHarvests().reduce((total, item) => {
                                                                                                                                                                                                                                                                                                                                            return total + Number(item.price);
                                                                                                                                                                                                                                                                                                                                                    }, 0);
                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                            getProfit() {
                                                                                                                                                                                                                                                                                                                                                                    return this.getTotalIncome() - this.getTotalExpenses();
                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                            // -------------------------
                                                                                                                                                                                                                                                                                                                                                                                // Backup & Restore
                                                                                                                                                                                                                                                                                                                                                                                    // -------------------------

                                                                                                                                                                                                                                                                                                                                                                                        exportData() {

                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                            expenses: this.getExpenses(),
                                                                                                                                                                                                                                                                                                                                                                                                                        harvests: this.getHarvests(),
                                                                                                                                                                                                                                                                                                                                                                                                                                    exportedAt: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                    importData(data) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data.expenses) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.saveExpenses(data.expenses);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (data.harvests) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.saveHarvests(data.harvests);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // -------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Clear
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // -------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clearAll() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.removeItem(STORAGE_KEYS.expenses);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                localStorage.removeItem(STORAGE_KEYS.harvests);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };